M48
; DRILL file {KiCad (6.0.4)} date Fri Aug  5 23:17:55 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-05T23:17:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.300
%
G90
G05
T1
X149.5Y-113.25
X153.0Y-113.25
T2
X132.0Y-102.75
X132.0Y-115.5
X156.257Y-115.747
X159.5Y-116.0
T3
X161.75Y-101.25
X161.75Y-113.95
T4
X152.5Y-101.65
X152.5Y-107.25
T0
M30
